In [25]:
# Importing libraries
import pandas as pd
import numpy as np

In [26]:
# Reading the excel to a dataframe
df = pd.read_excel("Group3_Dataset_of_Employee_Attrition.xlsx")

In [27]:
# Exploring the first 5 rows
df.head()

,ID,Attrition,Gender,Age,Maritalstatus,Academic_degree,Years_Experience,Years_experience_lastorganization,Sector,Department,...,Job_Engagement,Distance_to_work,Work_Live_Balance,Physical_Stress,Psychological_Exhaustion,Job_Stability,Health_Issues,Environment_Satisfaction,Job_Satisfaction,Job_Opportunities
0,11,Yes,Female,31 to 40,Married,Master's,Less than 5 years,Less than 5 years,Medical sector,Accounting,...,Medium,Medium,Medium,Yes,No,No,Yes,Medium,Not satisfied,Yes
1,12,No,Female,21 to 30,Single,Master's,Less than 5 years,Less than 5 years,Medical sector,Accounting,...,Medium,Medium,Medium,No,No,Yes,No,Medium,Satisfied,No
2,13,No,Female,21 to 30,Single,Bachelor's,Less than 5 years,Less than 5 years,Education sector,Teaching,...,Medium,Close,Medium,Yes,Sometimes,No,No,Medium,Satisfied,Yes
3,14,No,Female,21 to 30,Single,Bachelor's,Less than 5 years,Less than 5 years,Education sector,Teaching,...,Medium,Medium,Medium,Yes,Yes,No,No,Low,Not satisfied,No
4,15,No,Female,21 to 30,Single,Bachelor's,Less than 5 years,Less than 5 years,Education sector,Teaching,...,Medium,Medium,Medium,Sometimes,Sometimes,No,No,Medium,Not satisfied,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1186,1209,No,Female,21 to 30,Married,Bachelor's,From 5 to 10 years,From 5 to 10 years,Medical sector,Administration,...,Medium,Medium,Medium,No,No,Yes,No,Medium,Satisfied,No
1187,1210,No,Female,21 to 30,Married,Master's,From 5 to 10 years,From 5 to 10 years,Financial sector,Administration,...,Medium,Medium,Medium,Sometimes,No,Yes,No,Medium,Satisfied,No
1188,1211,Yes,Male,21 to 30,Single,Master's,From 5 to 10 years,Less than 5 years,Energy sector,Processes,...,Medium,Close,Medium,No,Yes,Yes,Yes,Medium,Satisfied,Yes
1189,1212,Yes,Female,31 to 40,Married,Master's,From 5 to 10 years,Less than 5 years,Education sector,Relations,...,Easy,Far,Medium,Yes,Yes,No,No,High,Not satisfied,Yes
1190,1213,No,Female,21 to 30,Single,Master's,Less than 5 years,Less than 5 years,Education sector,Administration,...,Medium,Medium,Medium,Yes,Yes,Yes,No,Medium,Satisfied,No

In [28]:
# Exploring general dataset information
print("Dataset information:")
print(df.info())

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 1191 entries, 0 to 1190
Data columns (total 35 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   ID                                          1191 non-null   int64
 1   Attrition                                   1191 non-null   str
 2   Gender                                      1191 non-null   str
 3   Age                                         1191 non-null   str
 4    Maritalstatus                              1191 non-null   str
 5    Academic_degree                            1191 non-null   str
 6   Years_Experience                            1191 non-null   str
 7   Years_experience_lastorganization           1191 non-null   str
 8   Sector                                      1191 non-null   str
 9   Department                                  1191 non-null   str
 10  JobTitle                                    1191 non-null   str
 11  MonthlySalary                               1191 non-null   str
 12  Allowances                                  1191 non-null   int64
 13  MedicalInsurance                            1191 non-null   str
 14  Bonus                                       1191 non-null   str
 15  OverTime                                    1191 non-null   str
 16  Payment_Overtime                            1191 non-null   str
 17  Rewards&Wages_Satisfaction                  1191 non-null   str
 18  Get_ Deserved_Promotion                     1191 non-null   str
 19  Training_programs_ During_last_three_years  1191 non-null   str
 20  Useful_Training_Programs                    1191 non-null   str
 21  Business_Travel                             1191 non-null   str
 22  Job_Support                                 1191 non-null   str
 23  Recognition                                 1191 non-null   str
 24  Emotional_Commitment                        1191 non-null   str
 25  Job_Engagement                              1191 non-null   str
 26  Distance_to_work                            1191 non-null   str
 27  Work_Live_Balance                           1191 non-null   str
 28  Physical_Stress                             1191 non-null   str
 29  Psychological_Exhaustion                    1191 non-null   str
 30  Job_Stability                               1191 non-null   str
 31  Health_Issues                               1191 non-null   str
 32  Environment_Satisfaction                    1191 non-null   str
 33  Job_Satisfaction                            1191 non-null   str
 34  Job_Opportunities                           1191 non-null   str
dtypes: int64(2), str(33)
memory usage: 325.8 KB
None

In [29]:
# Dropping the ID column because it does not have any useful information
df = df.drop(columns=["ID"])

In [30]:
# Normalizing the column names
df.columns = df.columns.str.strip().str.replace(" ","_")

In [31]:
# First 5 rows
df.head()

,Attrition,Gender,Age,Maritalstatus,Academic_degree,Years_Experience,Years_experience_lastorganization,Sector,Department,JobTitle,...,Job_Engagement,Distance_to_work,Work_Live_Balance,Physical_Stress,Psychological_Exhaustion,Job_Stability,Health_Issues,Environment_Satisfaction,Job_Satisfaction,Job_Opportunities
0,Yes,Female,31 to 40,Married,Master's,Less than 5 years,Less than 5 years,Medical sector,Accounting,Accountant,...,Medium,Medium,Medium,Yes,No,No,Yes,Medium,Not satisfied,Yes
1,No,Female,21 to 30,Single,Master's,Less than 5 years,Less than 5 years,Medical sector,Accounting,Accountant,...,Medium,Medium,Medium,No,No,Yes,No,Medium,Satisfied,No
2,No,Female,21 to 30,Single,Bachelor's,Less than 5 years,Less than 5 years,Education sector,Teaching,Teacher,...,Medium,Close,Medium,Yes,Sometimes,No,No,Medium,Satisfied,Yes
3,No,Female,21 to 30,Single,Bachelor's,Less than 5 years,Less than 5 years,Education sector,Teaching,Teacher,...,Medium,Medium,Medium,Yes,Yes,No,No,Low,Not satisfied,No
4,No,Female,21 to 30,Single,Bachelor's,Less than 5 years,Less than 5 years,Education sector,Teaching,Teacher,...,Medium,Medium,Medium,Sometimes,Sometimes,No,No,Medium,Not satisfied,No

In [21]:
# Exploring Statistical information of all columns values
print("Statistical description:")
df.describe()

Statistical description:

        Allowances
count  1191.000000
mean      1.222502
std       1.187483
min       0.000000
25%       0.000000
50%       1.000000
75%       2.000000
max       4.000000

In [22]:
# Exploring missing values
print("Missing values:")
print(df.isnull().sum())

Missing values:
Attrition                                     0
Gender                                        0
Age                                           0
 Maritalstatus                                0
 Academic_degree                              0
Years_Experience                              0
Years_experience_lastorganization             0
Sector                                        0
Department                                    0
JobTitle                                      0
MonthlySalary                                 0
Allowances                                    0
MedicalInsurance                              0
Bonus                                         0
OverTime                                      0
Payment_Overtime                              0
Rewards&Wages_Satisfaction                    0
Get_ Deserved_Promotion                       0
Training_programs_ During_last_three_years    0
Useful_Training_Programs                      0
Business_Travel                               0
Job_Support                                   0
Recognition                                   0
Emotional_Commitment                          0
Job_Engagement                                0
Distance_to_work                              0
Work_Live_Balance                             0
Physical_Stress                               0
Psychological_Exhaustion                      0
Job_Stability                                 0
Health_Issues                                 0
Environment_Satisfaction                      0
Job_Satisfaction                              0
Job_Opportunities                             0
dtype: int64